### ISSUE TITLE
Fix concurrency

### ISSUE THREAD

**Issue by juanlucruz** [sonata-nfv/tng-sp-ia-wtapi#16]
Is it needed?
Concurrency for task flow?
Concurrency for call requesting?

**Comment by jbonnet** [comment]
Suggestion: first make it work without concurrency. Then, if needed, optimize it, namely with concurrency.

My 2 cents

**Comment by juanlucruz** [comment]
No need of concurrency when creating different flows since provisioning is reasonably quick.
